name: CI/CD com Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Build da Imagem Docker
        run: docker build -t micaelbf/allbooks:1.2 .

      - name: Login no Docker Hub
        run: echo ${{ secrets.Ak47mica@ }} | docker login -u ${{ secrets.micaelbf }} --password-stdin

      - name: Push da Imagem Docker
        run: docker push micaelbf/allbooks:1.2
